# Generated by Django 5.2.7 on 2025-10-05 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateTimeField()),
                ('notificacion_valor', models.PositiveIntegerField(default=7)),
                ('notificacion_unidad', models.CharField(choices=[('días', 'Días'), ('meses', 'Meses')], default='días', max_length=50)),
                ('es_publico', models.BooleanField(default=True)),
                ('notificacion_enviada', models.BooleanField(default=False)),
                ('fecha_notificacion', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_creados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArchivoAdjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='eventos_adjuntos/')),
                ('nombre_original', models.CharField(max_length=255)),
                ('tipo_mime', models.CharField(max_length=100)),
                ('tamaño_bytes', models.PositiveIntegerField()),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_adjuntos', to='records.evento')),
            ],
        ),
        migrations.CreateModel(
            name='EventoUsuarioNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.evento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('evento', 'usuario')},
            },
        ),
        migrations.AddField(
            model_name='evento',
            name='notificar_a',
            field=models.ManyToManyField(blank=True, related_name='eventos_a_notificar', through='records.EventoUsuarioNotificacion', to=settings.AUTH_USER_MODEL),
        ),
    ]
