# Generated by Django 5.1.1 on 2025-10-07 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
