# Generated by Django 5.2.7 on 2025-10-11 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
