# Generated by Django 5.1.1 on 2025-10-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usuario_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='microsoft_access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='microsoft_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='microsoft_refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
