# Generated by Django 5.1.1 on 2025-11-24 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usuario_microsoft_access_token_usuario_microsoft_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='Designa si el usuario tiene privilegios de administrador'),
        ),
    ]
